vision: |
  OpenClaw is a personal AI assistant platform.
  We accept: bug fixes, performance improvements, new skills, documentation.
  We reject: unrelated features, breaking API changes without discussion,
  AI-generated PRs that do not follow CONTRIBUTING.md.

duplicate_threshold: 0.85
vision_model: gpt-4o-mini
labels:
  duplicate: "prguard:duplicate"
  off_scope: "prguard:off-scope"
  on_track: "prguard:on-track"
  needs_review: "prguard:needs-review"
  recommended: "prguard:recommended"

quality_thresholds:
  approve: 0.75
  reject: 0.45

max_diff_lines: 10000
skip_bots: true
dry_run: false

trusted_users:
  - steipete
  - dependabot[bot]
